[package]
name = "game_of_life"
version = "0.1.0"
authors = ["jonathansty <7695731+jonathansty@users.noreply.github.com>"]
edition = '2018'

[dependencies]
rand = "0.5"

[dependencies.glw]
path = "rs-glw"
