[package]
name = "game_of_life"
version = "0.1.0"
authors = ["jonathansty <7695731+jonathansty@users.noreply.github.com>"]

[dependencies]
glfw = "*"
rand = "*"
# glw = "0.1.2"
glw = { path = "../rs-glw" }
gl = "0.10.0"
